---
abstract: 'PPPort for Dist::Zilla'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::DZil: 0
  Test::Kwalitee: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PPPort
requires:
  Devel::PPPort: 0
  Dist::Zilla::Role::FileGatherer: 0
  Moose: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-PPPort
  repository: git://github.com/Leont/dist-zilla-plugin-ppport.git
version: 0.001
